{% set name = "euklid" %}
{% set version = "0.2.5" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/airgproducts/euklid/archive/{{ version }}.tar.gz
  sha256: 0f55d115b89e5a4febe1b19074160e47abbb565ab2803d0db422c784bb1d5488
build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --install-option="--conda" -vv
  script_env:
    - CMAKE_GENERATOR=Ninja

requirements:
  build:
    - {{ compiler('cxx') }}
    - ninja
    - cmake
  host:
    - pip
    - python
    - pybind11
    - eigen
    - mypy
    - libgomp      # [linux]
    - llvm-openmp      # [osx]
  run:
    - python

test:
  imports:
    - euklid

about:
  home: https://github.com/airgproducts/euklid
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A c++ library with bindings for python to help dealing with common CAD-like operations
  doc_url: https://github.com/airgproducts/euklid
  dev_url: https://github.com/airgproducts/euklid

extra:
  recipe-maintainers:
    - looooo
    - hiaselhans
